#!/usr/bin/env sh

set -e # errexit
set -u # nounset

ProjectDir="$(cd "$(dirname "$0")/.." && pwd)"

for pkg; do
        if test ! -e "$pkg"; then
                continue
        fi

        echo "Cleaning $(basename "$pkg")..."

        rm -rf "$pkg/node_modules" || true
        rm -fv "$pkg/package-lock.json" || true
        rm -fv "$pkg/.tsbuildinfo" || true

        find "$pkg" \
                \( -iname "*.js" -or -iname "*.jsx" -or -iname "*.d.ts" \) \
                -not -ipath "*/node_modules/*" \
                -exec rm -v "{}" + \
                2> /dev/null \
                || true
done
