#!/usr/bin/env bash

set -e # errexit
set -u # nounset

ProjectDir="$(cd "$(dirname "$0")/.." && pwd)"

: ${Git:=git}
: ${GitCleanArgs:=-X --force}
: ${GitCleanMoreArgs:=} # --dry-run,-n

for pkg; do
        if test ! -e "$pkg/package.json"; then
                echo "Invalid package '$pkg'. Skipping"
                continue
        fi

        (
                case "$pkg" in
                        /*) cd "$pkg";;
                        *) cd "$PWD/$pkg";;
                esac

                echo "Cleaning $(basename "$pkg")..."

                set -- $GitCleanArgs $GitCleanMoreArgs
                $Git clean "$@" .

                # rm -rf "$pkg/node_modules" || true
                # rm -fv "$pkg/package-lock.json" || true
                # rm -fv "$pkg/.tsbuildinfo" || true
                #
                # find "$pkg" \
                #         \( -iname "*.js" -or -iname "*.jsx"\) \
                #         -not -ipath "*/node_modules/*" \
                #         -exec rm -v "{}" + \
                #         2> /dev/null \
                #         || true
        )
done
