#!/usr/bin/env sh

# Inits all packages in the right order and with their production and development
# dependencies. Used to bootstrap the development environment of the packages.
# For only linking the monorepo packages without installing external dependencies,
# see `init-links`.
#
# EXAMPLE
# ./init

ProjectDir="$(cd "$(dirname "$0")/.." && pwd)"

. "$ProjectDir/tools/env.sh"
. "$ProjectDir/tools/env-styles.sh"

: ${Npm:=npm}
: ${NpmInstallCmd:=install}
: ${NpmInstallArgs:=--color false --no-progress}

init() {(
        local pkg="$1"
        shift

        cd "$pkg"

        echo "Initing ${GreenStyle}$(basename "$pkg")${ResetStyle}..."
        printf -- "${GrayStyle}"

        echo "Cleaning node_modules"
        rm -rf node_modules

        (
        echo "Installing deps"
        set -- $NpmInstallCmd $NpmInstallArgs
        if ! $Npm "$@"; then
                printf -- "${ResetStyle}"
                exit 1
        fi
        )

        (
        for dep in ./node_modules/@eviljs/std-*; do
                if test ! -e "$dep"; then
                        continue
                fi
                dep_name="$(basename "$dep")"
                echo "Linking $dep_name"
                rm -rf "node_modules/@eviljs/$dep_name"
                ln -s ../../../$dep_name node_modules/@eviljs/
        done
        )

        printf -- "${ResetStyle}"
)}

if test $# -eq 0; then
        set -- "$ProjectDir/std-"*
fi

for pkg; do
        init "$pkg"
done

echo "${GreenStyle}done${ResetStyle}"
