#!/usr/bin/env bash

# Bumps up a package version and publishes it.
#
# EXAMPLE
# PublishVersion=minor ./package-publish ./packages/evil*

set -e # errexit
set -u # nounset

Dir="$(cd "$(dirname "$0")/.." && pwd)"

: ${PublishVersion:=patch}
: ${Npm:=npm}
: ${NpmVersionCmd:=version}
: ${NpmVersionArgs:=--no-git-tag-version}
: ${NpmPublishCmd:=publish}
: ${NpmPublishArgs:=--access public}

for pkg; do
        if test ! -e "$pkg/package.json"; then
                echo "skipping invalid package '$pkg'."
                continue
        fi

        (
                case "$pkg" in
                        /*) cd "$pkg";;
                        *) cd "$PWD/$pkg";;
                esac

                set -- $NpmVersionCmd $NpmVersionArgs $PublishVersion
                $Npm "$@"
                printf -- 'Press Enter to continue'
                read answer
                set -- $NpmPublishCmd $NpmPublishArgs

                until $Npm "$@"; do
                        printf -- 'Press Enter to retry'
                        read answer
                done
        )
done
