#!/usr/bin/env bash

# Commits changes, bumps up package version and publishes it.
#
# EXAMPLE
# PublishVersion=minor ./package-publish-commit ./packages/evil*

set -e # errexit
set -u # nounset

Dir="$(cd "$(dirname "$0")/.." && pwd)"

: ${Git:=git}

for pkg; do
        if test ! -e "$pkg/package.json"; then
                echo "skipping invalid package '$pkg'."
                continue
        fi

        pkg_name=$(basename "$pkg")

        "$Dir/tools/package-build" "$pkg"

        $Git -C "$pkg" add --all .
        $Git -C "$pkg" commit --edit --message "($pkg_name) MESSAGE"

        "$Dir/tools/package-publish" "$pkg"

        pkg_version=$(npm --prefix "$pkg" pkg get version | tr -d '"')

        $Git -C "$pkg" add --all .
        $Git -C "$pkg" commit --message "($pkg_name) v$pkg_version"
done
