#!/usr/bin/env bash

set -e # errexit
set -u # nounset

# EXAMPLE
# ./build-package ./packages/evil*

Dir="$(cd "$(dirname "$0")/.." && pwd)"

: ${Npm:=npm}

build() {
        local pkg="$1"

        (
                case "$pkg" in
                        /*) cd "$pkg";;
                        *) cd "$PWD/$pkg";;
                esac

                $Npm run build --if-present
        )
}

for pkg; do
        if test ! -e "$pkg/package.json"; then
                echo "skipping invalid package '$pkg'."
                continue
        fi

        build "$pkg"
done
