#!/usr/bin/env sh

# Commits changes, bumps up package version and publishes it.
#
# EXAMPLE
# PublishVersion=minor ./package-publish-commit ./packages/@eviljs/*

set -e # errexit
set -u # nounset

Dir="$(cd "$(dirname "$0")/.." && pwd)"

: ${Git:=git}
: ${Npm:=npm}

for pkg; do
    if test ! -e "$pkg/package.json"; then
        echo "skipping invalid package '$pkg'."
        continue
    fi

    pkg_name=$(npm --prefix "$pkg" pkg get name | tr -d '"')

    $Npm --prefix "$pkg" run --if-present build
    $Git -C "$pkg" add --all .
    $Git -C "$pkg" commit --edit --message "($pkg_name) "

    "$Dir/tools/package-publish" "$pkg"

    pkg_version=$(npm --prefix "$pkg" pkg get version | tr -d '"')

    $Git -C "$pkg" add --all .
    $Git -C "$pkg" commit --message "($pkg_name) v$pkg_version"
done
