#!/usr/bin/env bash

set -e # errexit
set -u # nounset

# Inits package dependencies.
#
# EXAMPLE
# ./init-package ./packages/evil*

Dir="$(cd "$(dirname "$0")/.." && pwd)"

: ${Git:=git}
: ${Npm:=npm}

init() {
        local pkg="$1"

        "$Dir/tools/package-clean" "$pkg"

        (
        case "$pkg" in
                /*) cd "$pkg";;
                *) cd "$PWD/$pkg";;
        esac

        # --no-package-lock ignores the shrinkwrap.json too.
        $Npm install --global-style
        )

        link "$pkg" evilcss
        link "$pkg" eviljs
}

link() {
        local pkg="$1"
        local scope="$2"

        for dep in "$pkg/node_modules/@$scope/"*; do
                if test ! -e "$dep"; then
                        continue
                fi

                dep_name="$(basename "$dep")"
                echo "linking @$scope/$dep_name"
                rm -rf "$dep"
                ln -s "../../../$scope-$dep_name" "$pkg/node_modules/@$scope/$dep_name"
        done
}

for pkg; do
        if test ! -e "$pkg/package.json"; then
                echo "skipping invalid package '$pkg'."
                continue
        fi

        init "$pkg"
done
