#!/usr/bin/env sh

# Upgrades the dependencies of the packages.
#
# EXAMPLE
# ./package-upgrade ./packages/@eviljs/*

set -e # errexit
set -u # nounset

Dir="$(cd "$(dirname "$0")/.." && pwd)"

: ${NpmUpgrade:=npx npm-upgrade}
: ${NpmUpgradeArgs:=}

for pkg; do
    if test ! -e "$pkg/package.json"; then
        echo "skipping invalid package '$pkg'."
        continue
    fi

    (
        case "$pkg" in
            /*) cd "$pkg";;
            *) cd "$PWD/$pkg";;
        esac

        set -- $NpmUpgradeArgs
        $NpmUpgrade "$@"
    )
done
