#!/usr/bin/env sh

# Bumps up a package version and publishes it.
#
# EXAMPLE
# ReleaseVersion=minor ./release ./std-lib

if test $# -eq 0; then
        echo " Usage: $(basename "$0") <pkg_dir>"
        exit 1
fi
if test ! -e "$1"; then
        echo "Package '$1' not found."
        exit 1
fi

ProjectDir="$(cd "$(dirname "$0")/.." && pwd)"

. "$ProjectDir/tools/env.sh"
. "$ProjectDir/tools/env-styles.sh"

: ${ReleaseVersion:=patch}
: ${Npm:=npm}
: ${NpmVersionCmd:=version}
: ${NpmVersionArgs:=--no-git-tag-version}
: ${NpmPublishCmd:=publish}
: ${NpmPublishArgs:=--access public}

case "$1" in
        /*) cd "$1";;
        *) cd "$PWD/$1";;
esac
shift

set -- $NpmVersionCmd $NpmVersionArgs $ReleaseVersion
$Npm "$@"
printf -- 'Press Enter to continue'
read answer
set -- $NpmPublishCmd $NpmPublishArgs
$Npm "$@"
echo "${GreenStyle}done${ResetStyle}"