#!/usr/bin/env bash

# Upgrades the dependencies of the packages.
#
# EXAMPLE
# ./upgrade
# ./upgrade ./packages/std

set -e # errexit
set -u # nounset

ProjectDir="$(cd "$(dirname "$0")/.." && pwd)"

: ${NpmUpgrade:=npx npm-upgrade}
: ${NpmUpgradeArgs:=}

for pkg; do
        if test ! -e "$pkg/package.json"; then
                echo "Invalid package '$pkg'. Skipping"
                continue
        fi

        (
                case "$pkg" in
                        /*) cd "$pkg";;
                        *) cd "$PWD/$pkg";;
                esac

                set -- $NpmUpgradeArgs
                $NpmUpgrade "$@"
        )
done
