#!/usr/bin/env sh

# Upgrades the dependencies of the packages.
#
# EXAMPLE
# ./upgrade
# ./upgrade ./std-lib

set -e # errexit
set -u # nounset

ProjectDir="$(cd "$(dirname "$0")/.." && pwd)"

: ${NpmUpgrade:=npx npm-upgrade}
: ${NpmUpgradeArgs:=}

for pkg; do (
        if test ! -e "$pkg"; then
                echo "Package '$pkg' not found."
                exit 1
        fi

        case "$pkg" in
                /*) cd "$pkg";;
                *) cd "$PWD/$pkg";;
        esac

        set -- $NpmUpgradeArgs
        $NpmUpgrade "$@"
) done
